os: linux
language: node_js
node_js:
  - 14

branches:
  only:
    - main

before_script:
  - yarn

# Must change
script:
  - yarn lint
  - yarn test-coverage-upload
  - yarn build
  - yarn docs

deploy:
  - provider: npm
    cleanup: true
    email: $NPM_EMAIL
    api_token: $NPM_TOKEN
    on:
      branch: main

  - provider: pages
    cleanup: true
    local_dir: docs/
    token: $GITHUB_TOKEN
    on:
      branch: main
