os: linux
language: node_js
node_js:
  - 14

branches:
  only:
    - main

before_script:
  - yarn

script:
  - yarn lint
  - yarn test:unit --coverage
  - yarn test:integration --coverage
  - yarn compile

deploy:
  - provider: npm
    skip_cleanup: true
    email: $NPM_EMAIL
    api_token: $NPM_TOKEN
    on:
      branch: main