os: linux
language: node_js
node_js:
  - 14

stages:
  - name: Build and test
    if: branch = main
  - name: Deploy
    if: branch = main AND type = push


install:
  - yarn install --frozen-lockfile

jobs:
  include:
    - stage: Build and test
      script:
        - yarn lint
        - yarn test:unit --coverage
        - yarn test:integration --coverage
        - yarn compile

    - stage: Deploy
      script: yarn compile
      deploy:
        - provider: npm
          skip_cleanup: true
          email: $NPM_EMAIL
          api_token: $NPM_TOKEN
          on:
            branch: main