export enum BoilerplatePrefix {
  BOILERPLATE_BASIC = 'boilerplate-basic',
  BOILERPLATE_API = 'boilerplate-api',
  BOILERPLATE_API_STORE = 'boilerplate-api-store',
  BOILERPLATE_API_BROKER = 'boilerplate-api-broker',
  BOILERPLATE_IAC = 'boilerplate-iac',
  BOILERPLATE_PACKAGE = 'boilerplate-package',
  BOILERPLATE_COMPONENT = 'boilerplate-component',
  BOILERPLATE_WCS = 'boilerplate-wcs',
  BOILERPLATE_CRON = 'boilerplate-cron',
  BOILERPLATE_WCS_NEXT = 'boilerplate-wcs-next',
  BOILERPLATE_CMS_STORE = 'boilerplate-cms',
  BOILERPLATE_GO = 'boilerplate-go',
  BOILERPLATE_GO_API = 'boilerplate-go-api',
  BOILERPLATE_GO_STORE_API = 'boilerplate-go-api-store',
  BOILERPLATE_PYTHON = 'boilerplate-py',
}
